<?php
return [
    'service_manager' => [
        'abstract_factories' => [
            'Zend\Log\LoggerAbstractServiceFactory',
        ],
    ],
    'zenddb_repositories' => [
        'EnvironmentRepository' => [
            'aggregate_root_class' => 'KmbDomain\Model\Environment',
            'aggregate_root_proxy_factory' => 'KmbZendDbInfrastructure\Proxy\EnvironmentProxyFactory',
            'aggregate_root_hydrator_class' => 'KmbZendDbInfrastructure\Hydrator\EnvironmentHydrator',
            'table_name' => 'environments',
            'table_sequence_name' => 'environment_id_seq',
            'paths_table_name' => 'environments_paths',
            'factory' => 'KmbZendDbInfrastructure\Service\EnvironmentRepositoryFactory',
            'repository_class' => 'KmbZendDbInfrastructure\Service\EnvironmentRepository',
        ],
        'UserRepository' => [
            'aggregate_root_class' => 'KmbDomain\Model\User',
            'aggregate_root_hydrator_class' => 'KmbZendDbInfrastructure\Hydrator\UserHydrator',
            'table_name' => 'users',
            'table_sequence_name' => 'users_id_seq',
            'repository_class' => 'KmbZendDbInfrastructure\Service\UserRepository',
        ],
        'RevisionRepository' => [
            'aggregate_root_class' => 'KmbDomain\Model\Revision',
            'aggregate_root_proxy_factory' => 'KmbZendDbInfrastructure\Proxy\RevisionProxyFactory',
            'aggregate_root_hydrator_class' => 'KmbZendDbInfrastructure\Hydrator\RevisionHydrator',
            'table_name' => 'revisions',
            'table_sequence_name' => 'revisions_id_seq',
            'environment_class' => 'KmbDomain\Model\Environment',
            'environment_proxy_factory' => 'KmbZendDbInfrastructure\Proxy\EnvironmentProxyFactory',
            'environment_hydrator_class' => 'KmbZendDbInfrastructure\Hydrator\EnvironmentHydrator',
            'environment_table_name' => 'environments',
            'factory' => 'KmbZendDbInfrastructure\Service\RevisionRepositoryFactory',
            'repository_class' => 'KmbZendDbInfrastructure\Service\RevisionRepository',
        ],
        'GroupRepository' => [
            'aggregate_root_class' => 'KmbDomain\Model\Group',
            'aggregate_root_proxy_factory' => 'KmbZendDbInfrastructure\Proxy\GroupProxyFactory',
            'aggregate_root_hydrator_class' => 'KmbZendDbInfrastructure\Hydrator\GroupHydrator',
            'table_name' => 'groups',
            'table_sequence_name' => 'groups_id_seq',
            'revision_class' => 'KmbDomain\Model\Revision',
            'revision_proxy_factory' => 'KmbZendDbInfrastructure\Proxy\RevisionProxyFactory',
            'revision_hydrator_class' => 'KmbZendDbInfrastructure\Hydrator\RevisionHydrator',
            'revision_table_name' => 'revisions',
            'environment_class' => 'KmbDomain\Model\Environment',
            'environment_proxy_factory' => 'KmbZendDbInfrastructure\Proxy\EnvironmentProxyFactory',
            'environment_hydrator_class' => 'KmbZendDbInfrastructure\Hydrator\EnvironmentHydrator',
            'environment_table_name' => 'environments',
            'group_class_class' => 'KmbDomain\Model\GroupClass',
            'group_class_proxy_factory' => 'KmbZendDbInfrastructure\Proxy\GroupClassProxyFactory',
            'group_class_hydrator_class' => 'KmbZendDbInfrastructure\Hydrator\GroupClassHydrator',
            'group_class_table_name' => 'group_classes',
            'group_parameter_class' => 'KmbDomain\Model\GroupParameter',
            'group_parameter_proxy_factory' => 'KmbZendDbInfrastructure\Proxy\GroupParameterProxyFactory',
            'group_parameter_hydrator_class' => 'KmbZendDbInfrastructure\Hydrator\GroupParameterHydrator',
            'group_parameter_table_name' => 'group_parameters',
            'group_value_table_name' => 'group_values',
            'factory' => 'KmbZendDbInfrastructure\Service\GroupRepositoryFactory',
            'repository_class' => 'KmbZendDbInfrastructure\Service\GroupRepository',
        ],
        'GroupClassRepository' => [
            'aggregate_root_class' => 'KmbDomain\Model\GroupClass',
            'aggregate_root_proxy_factory' => 'KmbZendDbInfrastructure\Proxy\GroupClassProxyFactory',
            'aggregate_root_hydrator_class' => 'KmbZendDbInfrastructure\Hydrator\GroupClassHydrator',
            'table_name' => 'group_classes',
            'table_sequence_name' => 'group_classes_id_seq',
            'group_parameter_table_name' => 'group_parameters',
            'factory' => 'KmbZendDbInfrastructure\Service\GroupClassRepositoryFactory',
            'repository_class' => 'KmbZendDbInfrastructure\Service\GroupClassRepository',
        ],
        'GroupParameterRepository' => [
            'aggregate_root_class' => 'KmbDomain\Model\GroupParameter',
            'aggregate_root_proxy_factory' => 'KmbZendDbInfrastructure\Proxy\GroupParameterProxyFactory',
            'aggregate_root_hydrator_class' => 'KmbZendDbInfrastructure\Hydrator\GroupParameterHydrator',
            'table_name' => 'group_parameters',
            'table_sequence_name' => 'group_parameters_id_seq',
            'group_value_table_name' => 'group_values',
            'factory' => 'KmbZendDbInfrastructure\Service\GroupParameterRepositoryFactory',
            'repository_class' => 'KmbZendDbInfrastructure\Service\GroupParameterRepository',
        ],
    ],
];
