<?php
return [
    'service_manager' => [
        'abstract_factories' => [
            'Zend\Log\LoggerAbstractServiceFactory',
        ],
    ],
    'zenddb_repositories' => [
        'EnvironmentRepository' => [
            'aggregate_root_class' => 'KmbDomain\Model\Environment',
            'aggregate_root_proxy_factory' => 'KmbZendDbInfrastructure\Proxy\EnvironmentProxyFactory',
            'aggregate_root_hydrator_class' => 'KmbZendDbInfrastructure\Hydrator\EnvironmentHydrator',
            'table_name' => 'environments',
            'table_sequence_name' => 'environment_id_seq',
            'paths_table_name' => 'environments_paths',
            'factory' => 'KmbZendDbInfrastructure\Service\EnvironmentRepositoryFactory',
            'repository_class' => 'KmbZendDbInfrastructure\Service\EnvironmentRepository',
        ],
        'UserRepository' => [
            'aggregate_root_class' => 'KmbDomain\Model\User',
            'aggregate_root_hydrator_class' => 'KmbZendDbInfrastructure\Hydrator\UserHydrator',
            'table_name' => 'users',
            'table_sequence_name' => 'users_id_seq',
            'repository_class' => 'KmbZendDbInfrastructure\Service\UserRepository',
        ],
        'RevisionRepository' => [
            'aggregate_root_class' => 'KmbDomain\Model\Revision',
            'aggregate_root_proxy_factory' => 'KmbZendDbInfrastructure\Proxy\RevisionProxyFactory',
            'aggregate_root_hydrator_class' => 'KmbZendDbInfrastructure\Hydrator\RevisionHydrator',
            'table_name' => 'revisions',
            'table_sequence_name' => 'revisions_id_seq',
            'environment_class' => 'KmbDomain\Model\Environment',
            'environment_proxy_factory' => 'KmbZendDbInfrastructure\Proxy\EnvironmentProxyFactory',
            'environment_hydrator_class' => 'KmbZendDbInfrastructure\Hydrator\EnvironmentHydrator',
            'environment_table_name' => 'environments',
            'factory' => 'KmbZendDbInfrastructure\Service\RevisionRepositoryFactory',
            'repository_class' => 'KmbZendDbInfrastructure\Service\RevisionRepository',
        ],
        'GroupRepository' => [
            'aggregate_root_class' => 'KmbDomain\Model\Group',
            'aggregate_root_proxy_factory' => 'KmbZendDbInfrastructure\Proxy\GroupProxyFactory',
            'aggregate_root_hydrator_class' => 'KmbZendDbInfrastructure\Hydrator\GroupHydrator',
            'table_name' => 'groups',
            'table_sequence_name' => 'groups_id_seq',
            'revision_class' => 'KmbDomain\Model\Revision',
            'revision_proxy_factory' => 'KmbZendDbInfrastructure\Proxy\RevisionProxyFactory',
            'revision_hydrator_class' => 'KmbZendDbInfrastructure\Hydrator\RevisionHydrator',
            'revision_table_name' => 'revisions',
            'environment_class' => 'KmbDomain\Model\Environment',
            'environment_proxy_factory' => 'KmbZendDbInfrastructure\Proxy\EnvironmentProxyFactory',
            'environment_hydrator_class' => 'KmbZendDbInfrastructure\Hydrator\EnvironmentHydrator',
            'environment_table_name' => 'environments',
            'puppet_class_class' => 'KmbDomain\Model\PuppetClass',
            'puppet_class_proxy_factory' => 'KmbZendDbInfrastructure\Proxy\PuppetClassProxyFactory',
            'puppet_class_hydrator_class' => 'KmbZendDbInfrastructure\Hydrator\PuppetClassHydrator',
            'puppet_class_table_name' => 'puppet_classes',
            'parameter_class' => 'KmbDomain\Model\Parameter',
            'parameter_proxy_factory' => 'KmbZendDbInfrastructure\Proxy\ParameterProxyFactory',
            'parameter_hydrator_class' => 'KmbZendDbInfrastructure\Hydrator\ParameterHydrator',
            'parameter_table_name' => 'parameters',
            'value_class' => 'KmbDomain\Model\Value',
            'value_hydrator_class' => 'KmbZendDbInfrastructure\Hydrator\ValueHydrator',
            'value_table_name' => 'values',
            'factory' => 'KmbZendDbInfrastructure\Service\GroupRepositoryFactory',
            'repository_class' => 'KmbZendDbInfrastructure\Service\GroupRepository',
        ],
        'PuppetClassRepository' => [
            'aggregate_root_class' => 'KmbDomain\Model\PuppetClass',
            'aggregate_root_proxy_factory' => 'KmbZendDbInfrastructure\Proxy\PuppetClassProxyFactory',
            'aggregate_root_hydrator_class' => 'KmbZendDbInfrastructure\Hydrator\PuppetClassHydrator',
            'table_name' => 'puppet_classes',
            'table_sequence_name' => 'puppets_class_id_seq',
            'parameter_table_name' => 'parameters',
            'factory' => 'KmbZendDbInfrastructure\Service\PuppetClassRepositoryFactory',
            'repository_class' => 'KmbZendDbInfrastructure\Service\PuppetClassRepository',
        ],
        'ParameterRepository' => [
            'aggregate_root_class' => 'KmbDomain\Model\Parameter',
            'aggregate_root_proxy_factory' => 'KmbZendDbInfrastructure\Proxy\ParameterProxyFactory',
            'aggregate_root_hydrator_class' => 'KmbZendDbInfrastructure\Hydrator\ParameterHydrator',
            'table_name' => 'parameters',
            'table_sequence_name' => 'parameters_id_seq',
            'repository_class' => 'KmbZendDbInfrastructure\Service\ParameterRepository',
        ],
    ],
];
